# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dimensioner_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DimensionerWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1127, 904)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(230, 20, 781, 801))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_input_object_height = QtWidgets.QLabel(self.groupBox)
        self.label_input_object_height.setObjectName("label_input_object_height")
        self.gridLayout.addWidget(self.label_input_object_height, 0, 1, 1, 1)
        self.lineEdit_widht = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_widht.setText("")
        self.lineEdit_widht.setObjectName("lineEdit_widht")
        self.gridLayout.addWidget(self.lineEdit_widht, 1, 0, 1, 1)
        self.lineEdit_height = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_height.setText("")
        self.lineEdit_height.setObjectName("lineEdit_height")
        self.gridLayout.addWidget(self.lineEdit_height, 1, 1, 1, 1)
        self.label_input_widht = QtWidgets.QLabel(self.groupBox)
        self.label_input_widht.setObjectName("label_input_widht")
        self.gridLayout.addWidget(self.label_input_widht, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.pdfAdder = QtWidgets.QPushButton(self.widget)
        self.pdfAdder.setObjectName("pdfAdder")
        self.verticalLayout.addWidget(self.pdfAdder)
        self.pdfListWidget = QtWidgets.QListWidget(self.widget)
        self.pdfListWidget.setObjectName("pdfListWidget")
        self.verticalLayout.addWidget(self.pdfListWidget)
        self.pdfCreater = QtWidgets.QPushButton(self.widget)
        self.pdfCreater.setObjectName("pdfCreater")
        self.verticalLayout.addWidget(self.pdfCreater)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Object Output Dimension"))
        self.label_input_object_height.setText(_translate("MainWindow", "Height (mm)"))
        self.label_input_widht.setText(_translate("MainWindow", "Widht (mm)"))
        self.pdfAdder.setText(_translate("MainWindow", "Add PDF File"))
        self.pdfCreater.setText(_translate("MainWindow", "Create Dimensioned PDFs"))
