# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pagination_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PaginatorWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(250, 40, 301, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(10, 20, 274, 41))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_output_widht = QtWidgets.QLabel(self.widget)
        self.label_output_widht.setObjectName("label_output_widht")
        self.gridLayout.addWidget(self.label_output_widht, 0, 0, 1, 1)
        self.label_output_height = QtWidgets.QLabel(self.widget)
        self.label_output_height.setObjectName("label_output_height")
        self.gridLayout.addWidget(self.label_output_height, 0, 1, 1, 1)
        self.lineEdit_outpu_widht = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_outpu_widht.setObjectName("lineEdit_outpu_widht")
        self.gridLayout.addWidget(self.lineEdit_outpu_widht, 1, 0, 1, 1)
        self.lineEdit_output_height = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_output_height.setObjectName("lineEdit_output_height")
        self.gridLayout.addWidget(self.lineEdit_output_height, 1, 1, 1, 1)
        self.addPdfDimensioned = QtWidgets.QPushButton(self.centralwidget)
        self.addPdfDimensioned.setGeometry(QtCore.QRect(350, 230, 75, 23))
        self.addPdfDimensioned.setObjectName("addPdfDimensioned")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 330, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 21))
        self.menubar.setObjectName("menubar")
        self.menuPaginator = QtWidgets.QMenu(self.menubar)
        self.menuPaginator.setObjectName("menuPaginator")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuPaginator.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Output PDF Dimensions"))
        self.label_output_widht.setText(_translate("MainWindow", "Widht (mm)"))
        self.label_output_height.setText(_translate("MainWindow", "Height (mm)"))
        self.addPdfDimensioned.setText(_translate("MainWindow", "Select Pdf"))
        self.pushButton_2.setText(_translate("MainWindow", "Create PDF"))
        self.menuPaginator.setTitle(_translate("MainWindow", "Paginator"))
